import { BadgeDollarSign, CheckCircle2, Clock3, FilePlus2, Files, ReceiptText, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import Button from "../../components/common/Button";
import Card from "../../components/common/Card";
import Input from "../../components/common/Input";
import PageHeader from "../../components/common/PageHeader";
import StatCard from "../../components/common/StatCard";
import Table from "../../components/common/Table";
import LineItemsEditor, { type DocumentLineInput } from "../../components/documents/LineItemsEditor";
import { useAuth } from "../../context/AuthContext";
import { useErp } from "../../context/ErpContext";
import { apiRequest } from "../../lib/api";
import { formatCurrency, formatDate, formatNumber } from "../../lib/format";
import type { CompanySettings, Customer, Product, Quotation, QuotationStatus } from "../../types/erp";
import { appPaths } from "../../routes/navigation";

const statusLabels: Record<QuotationStatus, string> = { draft: "مسودة", sent: "مرسل", accepted: "مقبول", expired: "منتهي", rejected: "مرفوض" };
const statusStyles: Record<QuotationStatus, string> = { draft: "bg-slate-100 text-slate-600", sent: "bg-blue-50 text-blue-700", accepted: "bg-emerald-50 text-emerald-700", expired: "bg-amber-50 text-amber-700", rejected: "bg-rose-50 text-rose-700" };
type PageResult<T>={items:T[];page:number;limit:number;total:number};
type BootstrapResult={settings:CompanySettings};

function futureDate(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10);}

export default function Quotations(){
  const {user}=useAuth(); const erp=useErp(); const isProduction=user?.mode==="supabase";
  const [productionQuotes,setProductionQuotes]=useState<Quotation[]>([]),[productionCustomers,setProductionCustomers]=useState<Customer[]>([]),[productionProducts,setProductionProducts]=useState<Product[]>([]),[productionSettings,setProductionSettings]=useState<CompanySettings|null>(null);
  const quotations=isProduction?productionQuotes:erp.quotations, customers=isProduction?productionCustomers:erp.customers, products=isProduction?productionProducts:erp.products, settings=isProduction?(productionSettings??erp.settings):erp.settings;
  const [showForm,setShowForm]=useState(false),[search,setSearch]=useState(""),[customerId,setCustomerId]=useState(""),[issueDate,setIssueDate]=useState(()=>futureDate(0)),[expiryDate,setExpiryDate]=useState(()=>futureDate(14)),[status,setStatus]=useState<"draft"|"sent">("draft"),[taxRate,setTaxRate]=useState(settings.taxRate),[notes,setNotes]=useState(""),[items,setItems]=useState<DocumentLineInput[]>([]),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[loading,setLoading]=useState(isProduction),[saving,setSaving]=useState(false);
  const subtotal=useMemo(()=>items.reduce((sum,item)=>sum+item.quantity*item.unitAmount,0),[items]), total=subtotal*(1+Math.max(0,taxRate)/100), normalizedSearch=search.trim().toLowerCase(), filtered=quotations.filter(q=>!normalizedSearch||q.number.toLowerCase().includes(normalizedSearch)||q.customerName.toLowerCase().includes(normalizedSearch));

  async function loadProduction(){if(!isProduction)return;setLoading(true);try{const [quotes,customerPage,productPage,bootstrap]=await Promise.all([apiRequest<Quotation[]>("/quotations?limit=100"),apiRequest<PageResult<Customer>>("/erp/customers?limit=100&page=1"),apiRequest<PageResult<Product>>("/erp/products?limit=100&page=1"),apiRequest<BootstrapResult>("/erp/bootstrap")]);setProductionQuotes(quotes);setProductionCustomers(customerPage.items);setProductionProducts(productPage.items);setProductionSettings(bootstrap.settings);setTaxRate(current=>current===erp.settings.taxRate?bootstrap.settings.taxRate:current);setError(null);}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل عروض الأسعار.");}finally{setLoading(false);}}
  useEffect(()=>{void loadProduction();},[isProduction]);

  async function handleSave(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);try{if(isProduction){const result=await apiRequest<{quotation_number?:string}>("/quotations",{method:"POST",body:JSON.stringify({customerId,issueDate,expiryDate,status,taxRate,notes,items:items.map(item=>({productId:item.productId,quantity:item.quantity,unitPrice:item.unitAmount}))})});await loadProduction();setMessage(`تم إنشاء العرض ${result.quotation_number??""}.`);}else{const quotation=erp.createQuotation({customerId,issueDate,expiryDate,status,taxRate,notes,items:items.map(item=>({productId:item.productId,quantity:item.quantity,unitPrice:item.unitAmount}))});setMessage(`تم إنشاء العرض ${quotation.number}.`);}setCustomerId("");setItems([]);setNotes("");setError(null);setShowForm(false);}catch(e){setMessage(null);setError(e instanceof Error?e.message:"تعذر حفظ عرض السعر.");}finally{setSaving(false);}}
  async function updateStatus(id:string,next:QuotationStatus){try{if(isProduction){await apiRequest(`/quotations/${id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});await loadProduction();}else erp.updateQuotationStatus(id,next);setError(null);}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث حالة العرض.");}}
  async function handleConvert(id:string){const answer=window.prompt("طريقة دفع الفاتورة: اكتب نقدي أو بنك أو بطاقة أو آجل","آجل");if(!answer)return;const map:Record<string,string>={"نقدي":"cash","بنك":"bank","بطاقة":"card","آجل":"credit",cash:"cash",bank:"bank",card:"card",credit:"credit"};const method=map[answer.trim()];if(!method){setError("طريقة الدفع غير صحيحة.");return;}try{if(isProduction){const result=await apiRequest<{invoice_number?:string}>(`/quotations/${id}/convert`,{method:"POST",body:JSON.stringify({paymentMethod:method})});await loadProduction();setMessage(`تم تحويل العرض إلى الفاتورة ${result.invoice_number??""}.`);}else{const invoice=erp.convertQuotationToInvoice(id);setMessage(`تم تحويل العرض إلى الفاتورة ${invoice.number}.`);}setError(null);}catch(e){setMessage(null);setError(e instanceof Error?e.message:"تعذر تحويل عرض السعر.");}}

  return <div className="space-y-4">
    <PageHeader title="عروض الأسعار" description="أنشئ عروضًا احترافية وتابع قبولها قبل تحويلها إلى عملية بيع." eyebrow="المبيعات" actions={<Button onClick={()=>setShowForm(c=>!c)}>{showForm?<X size={15}/>:<FilePlus2 size={15}/>} {showForm?"إغلاق النموذج":"عرض سعر جديد"}</Button>}/>
    {message&&<div className="rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-[11px] font-bold text-emerald-700">{message}</div>}{error&&!showForm&&<div className="rounded-xl border border-rose-100 bg-rose-50 px-4 py-3 text-[11px] font-bold text-rose-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="إجمالي العروض" value={formatNumber(quotations.length)} icon={Files}/><StatCard title="العروض المقبولة" value={formatNumber(quotations.filter(i=>i.status==="accepted").length)} icon={CheckCircle2} tone="emerald"/><StatCard title="بانتظار الرد" value={formatNumber(quotations.filter(i=>i.status==="sent").length)} icon={Clock3} tone="amber"/><StatCard title="قيمة العروض" value={formatCurrency(quotations.reduce((s,i)=>s+i.total,0))} icon={BadgeDollarSign}/></div>
    {showForm&&<form onSubmit={handleSave} className="space-y-4"><Card>{error&&<div className="mb-4 rounded-xl bg-rose-50 p-3 text-[11px] text-rose-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-1.5"><label className="block text-[11px] font-bold text-slate-600">العميل</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="min-h-10 w-full rounded-[10px] border border-slate-200 px-3 text-xs" required><option value="">اختر العميل</option>{customers.filter(c=>c.status==="active").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><Input label="تاريخ الإصدار" type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/><Input label="صالح حتى" type="date" value={expiryDate} onChange={e=>setExpiryDate(e.target.value)} required/><div className="space-y-1.5"><label className="block text-[11px] font-bold text-slate-600">الحالة</label><select value={status} onChange={e=>setStatus(e.target.value as "draft"|"sent")} className="min-h-10 w-full rounded-[10px] border border-slate-200 px-3 text-xs"><option value="draft">مسودة</option><option value="sent">مرسل</option></select></div><Input label="الضريبة %" type="number" min="0" max="100" step="0.01" value={taxRate} onChange={e=>setTaxRate(Number(e.target.value))}/><div className="md:col-span-2 xl:col-span-3"><Input label="ملاحظات" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div></Card><LineItemsEditor products={products} items={items} mode="sale" onChange={setItems}/><Card className="flex items-center justify-between"><div><p className="text-[10px] text-slate-400">الإجمالي شامل الضريبة</p><p className="mt-1 text-2xl font-black">{formatCurrency(total)}</p></div><Button type="submit" loading={saving}><FilePlus2 size={15}/>حفظ عرض السعر</Button></Card></form>}
    <Card className="p-3"><label className="flex h-10 max-w-md items-center gap-2 rounded-[10px] border border-slate-200 bg-slate-50 px-3"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالرقم أو العميل..." className="min-w-0 flex-1 bg-transparent text-xs outline-none"/></label></Card>
    {loading?<Card className="text-center text-xs text-slate-500">جارٍ تحميل العروض...</Card>:<Table minWidth="940px"><thead><tr className="border-b bg-slate-50 text-[9px] text-slate-400"><th className="p-4">الرقم</th><th className="p-4">العميل</th><th className="p-4">الإصدار</th><th className="p-4">الصلاحية</th><th className="p-4">الإجمالي</th><th className="p-4">الحالة</th><th className="p-4">التحويل</th></tr></thead><tbody>{filtered.map(q=><tr key={q.id} className="border-b"><td className="p-4 font-mono text-[11px] font-bold text-blue-700">{q.number}</td><td className="p-4 text-xs font-bold">{q.customerName}</td><td className="p-4 text-[10px]">{formatDate(q.issueDate)}</td><td className="p-4 text-[10px]">{formatDate(q.expiryDate)}</td><td className="p-4 text-xs font-extrabold">{formatCurrency(q.total)}</td><td className="p-4"><select disabled={Boolean(q.convertedInvoiceId)} value={q.status} onChange={e=>void updateStatus(q.id,e.target.value as QuotationStatus)} className={`rounded-full border-0 px-2.5 py-1.5 text-[9px] font-bold ${statusStyles[q.status]}`}>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td className="p-4">{q.convertedInvoiceId?<Link to={appPaths.invoiceDetails(q.convertedInvoiceId)} className="text-[10px] font-bold text-blue-600">{q.convertedInvoiceNumber}</Link>:q.status==="accepted"?<Button size="sm" variant="secondary" onClick={()=>void handleConvert(q.id)}><ReceiptText size={13}/>تحويل</Button>:<span className="text-[9px] text-slate-400">اعتمد العرض أولاً</span>}</td></tr>)}{filtered.length===0&&<tr><td colSpan={7} className="p-12 text-center text-xs text-slate-400">لا توجد عروض مطابقة.</td></tr>}</tbody></Table>}
  </div>;
}
